---
- name: Check systemd version
  ansible.builtin.shell: systemd --version | awk 'NR==1 { print $2 }'
  check_mode: false
  register: systemd_version

- name: Add systemd-resolved config
  community.general.ini_file:
    path: /etc/systemd/resolved.conf.d/consul.conf
    state: present
    mode: 0644
    section: Resolve
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  loop:
    - { option: DNS, value: "127.0.0.1{{ dns_port }}" }
    - { option: Domains, value: "~consul" }
  vars:
    # Systemd version 246 and greater allow specifying a non-standard port on
    # the DNS server address.
    dns_port: "{{ (systemd_version.stdout|int >= 246) | ternary(':8600', '') }}"

- name: Create Envoy user account
  ansible.builtin.user:
    name: envoy
    create_home: no
    system: yes
